export default {
  name: 'showcaseItem',
  title: 'Showcase Item',
  type: 'document',
  fields: [
    {name: 'title', title: 'Title', type: 'array', of: [{type: 'block'}], validation: (r) => r.required()},
    {
      name: 'tool',
      title: 'Target Tool',
      type: 'string',
      options: { list: [
        { title: 'Seedream 4 (Image)', value: 'seedream4' },
        { title: 'Seedance (Video)', value: 'seedance' },
      ]},
      description: 'Which tool this template opens in',
    },
    {
      name: 'templateSlug',
      title: 'Template Slug',
      type: 'string',
      description: 'Slug of the DB template to load (e.g., pet-portrait-v1)',
    },
    {
      name: 'titleFontFamily',
      title: 'Title Font Family',
      type: 'string',
      options: {
        list: [
          {title: 'Helvetica', value: 'helvetica'},
          {title: 'Arial', value: 'arial'},
          {title: 'Times New Roman', value: 'times'},
          {title: 'Courier New', value: 'courier'},
          {title: 'Georgia', value: 'georgia'},
          {title: 'Verdana', value: 'verdana'},
          {title: 'Tahoma', value: 'tahoma'},
          {title: 'Trebuchet MS', value: 'trebuchet'},
          {title: 'Comic Sans MS', value: 'comic'},
          {title: 'Impact', value: 'impact'},
          {title: 'Lucida Console', value: 'lucida'},
          {title: 'Palatino', value: 'palatino'},
        ],
      },
      initialValue: 'helvetica',
      description: 'Choose the font family for the title text',
    },
    {name: 'caption', title: 'Caption', type: 'array', of: [{type: 'block'}]},
    {
      name: 'captionFontSize',
      title: 'Caption Font Size',
      type: 'string',
      options: {
        list: [
          {title: 'Small', value: 'text-xs'},
          {title: 'Medium', value: 'text-sm'},
          {title: 'Large', value: 'text-base'},
          {title: 'Extra Large', value: 'text-lg'},
        ],
      },
      initialValue: 'text-sm',
      description: 'Controls the size of the caption text on hover',
    },
    {
      name: 'mediaType',
      type: 'string',
      options: {list: ['image', 'video']},
      validation: (r) => r.required(),
    },
    {name: 'image', type: 'image', options: {hotspot: true}},
    {name: 'video', title: 'Video File', type: 'file'},
    {name: 'videoUrl', title: 'External Video URL', type: 'url'},
    {name: 'linkHref', title: 'Click Target', type: 'string'},
    {name: 'tags', type: 'array', of: [{type: 'string'}]},
    {
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'templateSection' }] }],
      description: 'Add this item to one or more template sections',
    },
    {name: 'featured', type: 'boolean', initialValue: false},
    {name: 'public', type: 'boolean', initialValue: true},
    {
      name: 'captionPlacement',
      type: 'string',
      options: {list: ['below', 'overlay', 'hover']},
      initialValue: 'overlay',
    },
    {name: 'variant', type: 'string', options: {list: ['standard', 'featured']}},
    {name: 'spanCols', type: 'number'},
    {name: 'spanRows', type: 'number'},
    {
      name: 'ratio',
      type: 'string',
      options: {list: ['1:1', '4:5', '3:2', '16:9']},
      initialValue: '16:9',
    },
    {name: 'publishedAt', type: 'datetime', initialValue: () => new Date().toISOString()},
  ],
}


